### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by Grommish** [davido/gerrit-oauth-provider#1]
I'm very interested in maintaining my Google OAuth, so I want to get this working.  I've got gerrit's source and built buck.  buck build gerrit and buck build release both worth.  I can build the core plugins and the api without error.

I clone this repo into the plugins directory and issue the buck build plugins/gerrit-oauth-provider and get the following.  What am I doing wrong?

donald@devbox7:~/gerrit$ buck build plugins/gerrit-oauth-provider
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 1.6s
[+] BUILDING...1.8s (216/218 JOBS)
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> IDLE
 |=> //plugins/gerrit-oauth-provider:gerrit-oauth-provider__plugin...  0.8s (running javac[0.8s])
 |=> IDLE
 |=> IDLE
 |=> IDLE
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:18: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthServiceProvider;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:19: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthToken;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:20: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthUserInfo;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:21: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthVerifier;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:43: error: cannot find symbol
class GitHubOAuthService implements OAuthServiceProvider {
                                    ^
  symbol: class OAuthServiceProvider
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:66: error: cannot find symbol
  public OAuthToken getRequestToken() {
         ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:71: error: cannot find symbol
  public OAuthUserInfo getUserInfo(OAuthToken token) throws IOException {
                                   ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:71: error: cannot find symbol
  public OAuthUserInfo getUserInfo(OAuthToken token) throws IOException {
         ^
  symbol:   class OAuthUserInfo
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:101: error: cannot find symbol
  public OAuthToken getAccessToken(OAuthToken rt,
                                   ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:102: error: cannot find symbol
      OAuthVerifier rv) {
      ^
  symbol:   class OAuthVerifier
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:101: error: cannot find symbol
  public OAuthToken getAccessToken(OAuthToken rt,
         ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:115: error: cannot find symbol
  public String getAuthorizationUrl(OAuthToken rt) {
                                    ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:18: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthServiceProvider;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:19: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthToken;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:20: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthUserInfo;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:21: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthVerifier;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:43: error: cannot find symbol
class GoogleOAuthService implements OAuthServiceProvider {
                                    ^
  symbol: class OAuthServiceProvider
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:67: error: cannot find symbol
  public OAuthToken getRequestToken() {
         ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:72: error: cannot find symbol
  public OAuthUserInfo getUserInfo(OAuthToken token) throws IOException {
                                   ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:72: error: cannot find symbol
  public OAuthUserInfo getUserInfo(OAuthToken token) throws IOException {
         ^
  symbol:   class OAuthUserInfo
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:101: error: cannot find symbol
  public OAuthToken getAccessToken(OAuthToken rt,
                                   ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:102: error: cannot find symbol
      OAuthVerifier rv) {
      ^
  symbol:   class OAuthVerifier
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:101: error: cannot find symbol
  public OAuthToken getAccessToken(OAuthToken rt,
         ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:115: error: cannot find symbol
  public String getAuthorizationUrl(OAuthToken rt) {
                                    ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/HttpModule.java:19: error: package com.google.gerrit.extensions.auth.oauth does not exist
import com.google.gerrit.extensions.auth.oauth.OAuthServiceProvider;
                                              ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:65: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:90: error: cannot find symbol
      return new OAuthUserInfo(id.getAsString(),
                 ^
  symbol:   class OAuthUserInfo
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:70: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:109: error: cannot find symbol
    OAuthToken result = new OAuthToken(to.getToken(),
    ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:109: error: cannot find symbol
    OAuthToken result = new OAuthToken(to.getToken(),
                            ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GitHubOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:100: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:114: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:123: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java:128: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:66: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:90: error: cannot find symbol
      return new OAuthUserInfo(id.getAsString() /*externalId*/,
                 ^
  symbol:   class OAuthUserInfo
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:71: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:109: error: cannot find symbol
    OAuthToken result = new OAuthToken(to.getToken(),
    ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:109: error: cannot find symbol
    OAuthToken result = new OAuthToken(to.getToken(),
                            ^
  symbol:   class OAuthToken
  location: class com.googlesource.gerrit.plugins.oauth.GoogleOAuthService
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:100: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:114: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:123: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/GoogleOAuthService.java:128: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/HttpModule.java:42: error: cannot find symbol
      bind(OAuthServiceProvider.class)
           ^
  symbol:   class OAuthServiceProvider
  location: class com.googlesource.gerrit.plugins.oauth.HttpModule
/home/donald/gerrit/plugins/gerrit-oauth-provider/src/main/java/com/googlesource/gerrit/plugins/oauth/HttpModule.java:50: error: cannot find symbol
      bind(OAuthServiceProvider.class)
           ^
  symbol:   class OAuthServiceProvider
  location: class com.googlesource.gerrit.plugins.oauth.HttpModule
Errors: 45. Warnings: 0.
BUILD FAILED: //plugins/gerrit-oauth-provider:gerrit-oauth-provider__plugin failed with exit code 1:
javac

**Comment by davido** [comment]
Have you noticed the README.md, dependency section?

```
This plugin depends on OAuth extension point, exposed by this change: [1].
```

You havn't cherry-picked the mentioned change in your Gerrit tree, that why the build is failing.

It worth noting that needed change was cherry-picked to stable-2.10 branch and merged upstream. When you need master or 2.11-stable, you would need to cherry-pick the mentioned change, that was abandoned meantime: [1].

However, you may want to wait a bit, because i am working on adding support for linking OAuth identty to existing OpenID accounts. I will upload a new version of the extension point to gerrit-review and new plugin version to GitHub later today.

[1] https://gerrit-review.googlesource.com/65101
