### ISSUE TITLE
Switch account using oauth not working

### ISSUE THREAD

**Issue by rolandschulz** [davido/gerrit-oauth-provider#11]
Steps to reproduce:
- Being logged in (either with OpenID or OAuth)
- click switch account
- try to login (with either Google or GitHub)

Result:
Empty page. Nothing in error.log

Switching account and then logging in with OpenID works.

**Comment by davido** [comment]
Should be fixed in: [1].

* [1] https://gerrit-review.googlesource.com/67282

**Comment by pgeorgi** [comment]
works for me. Thanks for your efforts!

**Comment by davido** [comment]
@pgeorgi Thanks for testing and voting!

**Comment by davido** [comment]
Fixed in 2.10.4: [1].

[1] http://gerrit-documentation.storage.googleapis.com/ReleaseNotes/ReleaseNotes-2.10.4.html
