### ISSUE TITLE
Build the plugin for 2.15

### ISSUE THREAD

**Issue by bhcopeland** [davido/gerrit-oauth-provider#110]
https://gerrit-ci.gerritforge.com/view/Plugins-stable-2.15/

Do you think you could get a 2.15 in Gerrit's CI system?

Only got a 2.14 at the moment.

**Comment by davido** [comment]
The policy here is to only create stable branches, when really needed. Just use the plugin built from master and you should be fine: [1].

[1] https://gerrit-ci.gerritforge.com/view/Plugins-master/job/plugin-oauth-bazel-master-master/

**Comment by davido** [comment]
See also discussion on #106.
