### ISSUE TITLE
Can any share me the gerrit.conf for keyclock and settings in claim of keycloak for gerrit

### ISSUE THREAD

**Issue by davido** [davido/gerrit-oauth-provider#117]
_Originally posted by @mail2ganeshcse in https://github.com/davido/gerrit-oauth-provider/issues/109#issuecomment-457174763_

**Comment by davido** [comment]
Gerrit side should be as easy as this:

```
Gerrit side should be as easy as this:

```
[plugin "gerrit-oauth-provider-keycloak-oauth"]
    client-id = "<client-id>"
    client-secret = "<client-secret>"
```

**Comment by mail2ganeshcse** [comment]
[plugin "gerrit-oauth-provider-keycloak-oauth"]
    client-id = "<client-id>"
    client-secret = "<client-secret>"

Sorry Davido, i am not sure where to create the      client-secret = "<client-secret> from Keycloak

**Comment by mail2ganeshcse** [comment]
[plugin "gerrit-oauth-provider-keycloak-oauth"]
    client-id = "<client-id>"
    client-secret = "<client-secret>"

Sorry Davido, i am not sure where to create the      client-secret = "<client-secret> from Keycloak
Could you please share me any links to do the configuration for gerrit in keycloack console.

**Comment by davido** [comment]
I am not using KeyKloak myself, but may be this answer is helpful:

https://stackoverflow.com/questions/44752273/does-keycloak-client-id-has-a-secret

**Comment by mail2ganeshcse** [comment]
Thanks, but still i am getting the same issue url error, could you please suggest anyother opensoucre tool for gerrit oauth

**Comment by mail2ganeshcse** [comment]
[plugin "gerrit-oauth-provider-keycloak-oauth"]
root-url = https://18.223.24.200:8443
client-id = gerrit
client-secret = 8896724e-849c-4ee8-80c5-66730d6afc26
=============
this is my conf now.. (https://18.223.24.200:8443) this is my keycloak url ip.

**Comment by mail2ganeshcse** [comment]
i Follow the steps my conf are

Keycloak client settings
Root URL http://18.223.24.200:7070
* Valid Redirect URIs http://18.223.24.200:7070/*
Admin URL http://18.223.24.200:7070
Web Origins http://18.223.24.200:7070

Gerrit conf

[httpd]
        listenUrl = http://*:7070/
[cache]
        directory = cache
[plugin "gerrit-oauth-provider-keycloak-oauth"]
        root-url = https://18.223.24.200:8443
        realm = gerrit
        client-id = gerrit

But when i use to click login in gerrit it redirects to https://18.223.24.200:8443/auth/realms/gerrit/protocol/openid-connect/auth?client_id=gerrit&response_type=code&redirect_uri=http%3A%2F%2F18.223.24.200%3A7070%2Foauth&scope=openid&state=EblwxvYNLj11GvTK-KMd4TFQhe_7d2sYXnBeZHNOXW8

but 
We're sorry...
Page not found

Same issue...... not able to redirect

**Comment by davido** [comment]
What KeyCloak version are you using?

**Comment by mail2ganeshcse** [comment]
Version - 4.8.2.Final

**Comment by davido** [comment]
If this URL is wrong:

 https://18.223.24.200:8443/auth/realms/gerrit/protocol/openid-connect/auth?client_id=gerrit

can you try to figure out what is the right URL to login in KeyCloak?

**Comment by mail2ganeshcse** [comment]
I am not sure davido, but I tried with multiple times by checking but issue not solved so that I came here to get help from you

**Comment by mail2ganeshcse** [comment]
Even that url is auto generated when I click login button in gerrit so I couldn't find from where it takes how it process

**Comment by mail2ganeshcse** [comment]
https://18.223.24.200:8443
Admin/admin can you pls check it

**Comment by davido** [comment]
No I don't have time to do it.

Just follow this tutorial:

https://www.keycloak.org/docs/latest/authorization_services/index.html#_getting_started_hello_world_create_realm

1. Create a new realm, call it "main"
2.  Create a user call it "admin"
3. Create new Client-id, in realm "main" and call it "gerrit"

Then configure this: in gerrit:

```
[plugin "gerrit-oauth-provider-keycloak-oauth"]
    root-url = https://18.223.24.200:8443
    realm = main
    client-id = gerrit
    client-secret = 8896724e-849c-4ee8-80c5-66730d6afc26
```

**Comment by mail2ganeshcse** [comment]
@davido  please help me resolve the above java error.. i hope if this solved auth will work out.. as i have checked with keycloak side there is no error, since it pass the url and after that gerrit unable to catch it and throws above error.

**Comment by mail2ganeshcse** [comment]
Team Please help me to sort out the above issue.

**Comment by mail2ganeshcse** [comment]
@davido  Please help me to sort out the above issue.

**Comment by davido** [comment]
> Caused by: java.security.cert.CertificateException: No subject alternative names present

You have HTTPS communication and certificate issue.

According to [RFC 2818](https://tools.ietf.org/html/rfc2818):

```
Matching is performed using the matching rules specified by
   [RFC2459].  If more than one identity of a given type is present in
   the certificate (e.g., more than one dNSName name, a match in any one
   of the set is considered acceptable.) Names may contain the wildcard
   character * which is considered to match any single domain name
   component or component fragment. E.g., *.a.com matches foo.a.com but
   not bar.foo.a.com. f*.com matches foo.com but not bar.com.

   In some cases, the URI is specified as an IP address rather than a
   hostname. In this case, the iPAddress subjectAltName must be present
   in the certificate and must exactly match the IP in the URI.

   If the hostname does not match the identity in the certificate, user
   oriented clients MUST either notify the user (clients MAY give the
   user the opportunity to continue with the connection in any case) or
   terminate the connection with a bad certificate error.
```

Your SSL Certificate doesn't have `subjectAltName`, and you communicate from gerrit to KeyCloak using IP-Addresse, so that the default HostnameVerifier implementation works according to rfc2818, and act as it is specified in the spec:

```
  user   oriented clients MUST either notify the user (clients MAY give the
   user the opportunity to continue with the connection in any case) or
   terminate the connection with a bad certificate error.
```

That's why you are getting this exception. I think you have number of options:

1. Change your certificate and include subjectAltName that exactly matches the IP-Address
2. Don't use IP-Address, but use a hostname, that is matching certificate
3. Implement custom HostnameVerifier, that is skipping the test, or is checking for your specific host IPAddress, see this [example](https://stackoverflow.com/questions/42388953/customize-hostnameverifier-for-multiple-hosts-and-self-signed-certificate).

But note, that HTTPS issue has nothing to do with this gerrit plugin or with gerrit itself. You may want to switch to using HTTP protocol, to verify that Gerrit with KeyCloak OAuth integration works as expected, and sort out HTTPS + Certificate + IPAddress issue later.

**Comment by mail2ganeshcse** [comment]
thanks davido, anyways i have to check with keycloak, i have no idea how to do it, because by default when i install the keycloak it starts with those ports withh ssl cert.

**Comment by mail2ganeshcse** [comment]
NOpe david, it seems keycloak works on https only, when i try to change and run the port it says https is required.. pls find this below link..
http://35.237.244.29:8180

**Comment by davido** [comment]
It works here as expected. I created this repository: https://github.com/davido/keycloak-gerrit-oauth-provider and added there README.md with step-by step tutorial how to configure Gerrit with Keycloak OAuth2 provider.

I also added exported Keycloak gerrit client JSON file in resource directory in this repository and also added `gerrit.confg` file that I used to make that integration work.

I recommend you to follow this tutorial step-by step and find what is wrong on your side.

**Comment by mail2ganeshcse** [comment]
@davido  when i follow above instruction during the import json, i am gettign error like..

Error! Unable to parse JSON file...

**Comment by mail2ganeshcse** [comment]
@davido  i followed all above instruction, at finally i when i click at login page of gerrit it redirects to keycloak and it says error.

We're sorry...
HTTPS required

Please find the below log..


keycloak_1  | 04:00:29,190 WARN  [org.keycloak.events] (default task-17) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=148.64.6.114, error=ssl_required
keycloak_1  | 04:00:39,646 WARN  [org.keycloak.events] (default task-17) type=LOGIN_ERROR, realmId=master, clientId=null, userId=null, ipAddress=148.64.6.114, error=ssl_required

**Comment by davido** [comment]
Here is the right section in KeyCloak documentation how to set up HTTPS communication:

https://www.keycloak.org/docs/4.8/server_installation/index.html#enabling-ssl-https-for-the-keycloak-server

**Comment by mail2ganeshcse** [comment]
Thanks alot davido, finally it solved and now working without ssl..
