### ISSUE TITLE
Using Oauth HTTP --> Oauth is not working.

### ISSUE THREAD

**Issue by mail2ganeshcse** [davido/gerrit-oauth-provider#118]
Hi Davido, 

USing Oauth plugin SSO is working fine, but when i change the gitBasicAuthPolicy of
 gerrit.conf from HTTP to Oauth  is not working, it fails to push the but if i revert it back to HTTP, i can use it.. any idea

**Comment by davido** [comment]
`gitBasicAuthPolicy` is only supported to be HTTP in gerrit-oauth-provider plugin. See FAQ in this repository.
