### ISSUE TITLE
Linking identities with OAuth not working

### ISSUE THREAD

**Issue by rolandschulz** [davido/gerrit-oauth-provider#12]
Trying to link an OAuth identity produces an empty page (and nothing in error.log). This is with 2.10.2-1-g9ef3270 and #7.

**Comment by pgeorgi** [comment]
With 2.10.2-18-gc6c5e0b-dirty (the 0.2 release) I'm sent to http://$mygerrit/ouath?state=... with only a 'Not Found' error. Nothing in error.log either.

**Comment by davido** [comment]
Yes, this is not implemented.

**Comment by davido** [comment]
Shoud be fixed in: [1], [2].

* [1] https://gerrit-review.googlesource.com/67280
* [2] https://gerrit-review.googlesource.com/67281

**Comment by davido** [comment]
@rolandschulz Can you test it and vote verify and/or code-review upstream?

**Comment by pgeorgi** [comment]
works for me. Thanks for your efforts!

**Comment by davido** [comment]
@pgeorgi Thanks for testing and voting!

**Comment by lucamilanesio** [comment]
:+1: works for me, tested using both gerrit-oauth-provider and github-plugin to login to GitHub and linking the two external ids together.

**Comment by davido** [comment]
Fixed in 2.10.4: [1].

[1] http://gerrit-documentation.storage.googleapis.com/ReleaseNotes/ReleaseNotes-2.10.4.html
