### ISSUE TITLE
"Use X OAuth provider" prompts during init should default to what is currently configured

### ISSUE THREAD

**Issue by NoahAndrews** [davido/gerrit-oauth-provider#136]
I only want to use GitHub OAuth, but every time I update Gerrit I have to explicitly say no to setting up Google, BitBucket, CAS, Facebook, GitLab, Dex, Keycloak, Office365, and AirVantage. All of them default to yes. IMO, each one should default to no, unless it has already been configured.

**Comment by davido** [comment]
Thanks for the report, makes sense. Should be fixed in: [1]. Given that the problem affects Gerrit upgrade, I went ahead and applied it to stable-2.15 branch. Let's wait for the review and approval.

[1] https://gerrit-review.googlesource.com/c/plugins/oauth/+/253916
