### ISSUE TITLE
Plugin to create review on gerrit

### ISSUE THREAD

**Issue by rerrabolu** [davido/gerrit-oauth-provider#156]
Hi,

Unsure if this is the right place, but let me ask anyway.

Is there a Gerrit plugin that could to do the following:
 
-  Receive an email that has the code patch
-   Create a review on gerrit
-   Send email to list of folks about the new review

Could you advise me if such a thing exists.

Regards,
Ramesh

**Comment by davido** [comment]
I am not aware of such a thing.

I understand your use case though.LibreOffice project did this before moving to gerrit. Contributors just posted patches to the developer mailing list, and maintainers applied the patches, and did the review per mail. So they sent mail answer back with a statement like:

Line 42:

```
please change s/foo/bar.
```

It's about the review, isn't it, that would take place in browser anyway? 

If a user have a change in her workspace, to push it to Gerrit it's just:

```
  $ git push origin HEAD:refs/for/master
```

Why would I want to go to mail system instead?

**Comment by davido** [comment]
You could use this already: https://github.com/gitgitgadget/gitgitgadget
