### ISSUE TITLE
Account conflict after gerrit integrated office 365 login

### ISSUE THREAD

**Issue by liuzhangbeibei** [davido/gerrit-oauth-provider#157]
Currently using gerrit3.4.0
[plugin "gerrit-oauth-provider-azure-oauth"]
        tenant = 
        client-id = 
        fix-legacy-user-id = true
We used ldap to log in, and now we have integrated azure AAD and found the following problems:
. If the original account ldap user mailbox is the same as the aad user mailbox, aad will not be able to log in
. If the original account ldap user mailbox is inconsistent with the aad user mailbox, a new user will be created

can you help me? Thanks

**Comment by davido** [comment]
There is no out of the box support for migration from LDAP=>OAuth auth scheme.

You could migrate your user data from LDAP to OAuth I think.

**Comment by liuzhangbeibei** [comment]
Thanks
