### ISSUE TITLE
Hello，I login gerrit by oauth with gitlab，but no administrator rights，how to get？

### ISSUE THREAD

**Issue by Yanci516** [davido/gerrit-oauth-provider#159]

**Comment by davido** [comment]
In Gerrit, the first registered user is assigned administrator privilegies.
Please note, that this issue tracker only related to gerrit-oauth-provider plugin.

For questions and problem, consider to use other communication channels: [1].

Mailing list: https://groups.google.com/forum/#!forum/repo-discuss
Issue tracker: https://www.gerritcodereview.com/issues.html

[1] https://www.gerritcodereview.com/support.html
