### ISSUE TITLE
I have been pulling. Why is this?  Fetching @gerrit_plugin_api; fetching 446s

### ISSUE THREAD

**Issue by zhou1591** [davido/gerrit-oauth-provider#164]
![image](https://user-images.githubusercontent.com/39522200/168097526-2bb0fe4e-6c1e-4188-b040-8c1f27a43a6c.png)

- I have been pulling. Why is this?

- Fetching @gerrit_plugin_api; fetching 446s
- 
![image](https://user-images.githubusercontent.com/39522200/168099198-6e62c4cb-6787-4b83-bf41-abb67f87b2e9.png)

- After a while he will report an error

**Comment by davido** [comment]
Are you building in Windows?

This is not supported. Either build on Linux, or download bre-built artifact from GerritForge-CI: [1].

[1] https://gerrit-ci.gerritforge.com/view/Plugins-master/job/plugin-oauth-bazel-master-master/lastSuccessfulBuild/artifact/bazel-bin/plugins/oauth/oauth.jar
