### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hundanLi** [davido/gerrit-oauth-provider#165]
root@ubuntu1804:gerrit-oauth-provider# bazel build gerrit-oauth-provider
2022/06/08 17:20:00 Downloading https://releases.bazel.build/4.2.0/release/bazel-4.2.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
DEBUG: Rule 'com_googlesource_gerrit_bazlets' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1642236535 +0100"
DEBUG: Repository com_googlesource_gerrit_bazlets instantiated at:
  /mnt/d/project/company/gerrit-oauth-provider/WORKSPACE:5:13: in <toplevel>
  /mnt/d/project/company/gerrit-oauth-provider/bazlets.bzl:9:23: in load_bazlets
Repository rule git_repository defined at:
  /root/.cache/bazel/_bazel_root/7874537f8b64c481c63a0c1ad9038fc1/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
ERROR: Skipping 'gerrit-oauth-provider': no such target '//:gerrit-oauth-provider': target 'gerrit-oauth-provider' not declared in package '' defined by /mnt/d/project/company/gerrit-oauth-provider/BUILD
WARNING: Target pattern parsing failed.
ERROR: no such target '//:gerrit-oauth-provider': target 'gerrit-oauth-provider' not declared in package '' defined by /mnt/d/project/company/gerrit-oauth-provider/BUILD
INFO: Elapsed time: 47.448s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by davido** [comment]
Have you read the build instructions?

https://github.com/davido/gerrit-oauth-provider/blob/master/src/main/resources/Documentation/build.md

**Comment by hundanLi** [comment]
> 

Thanks, it would be better to put a link of building guide in readme.md
