### ISSUE TITLE
Build instructions are ambigous

### ISSUE THREAD

**Issue by silviuvulcan** [davido/gerrit-oauth-provider#17]
From the README.md:
```bash
git clone --recursive https://github.com/davido/gerrit-oauth-provider.git
cd gerrit-oauth-provider && buck build plugin
```
From the WIKI:
To build the plugin, Gerrit 2.10.1 release must be used. Given that plugin doesn't support standalone build mode yet, Gerrit must be cloned and build first. See the instructions and prerequisites for building Gerrit: .

to build the plugin, issue the following command:
```bash
  $ cd <gerrit>
  $ buck build plugins/gerrit-oauth-provider
```
and this one doesn't work

**Comment by davido** [comment]
Yes, Wiki is outdated. Gerrit 2.10.2 was released and should be used.
Instructions for in-tree build mode are not quite complete. Linking the plugin
directory to `plugins` directory in gerrit tree is missing. See `build.md` in
Documentation directory.

**Comment by silviuvulcan** [comment]
Thank you, indeed following the build.md instructions for building in tree it appears to be working. At least it's starting now.

Thank you.
