### ISSUE TITLE
Uneasy plug-in build

### ISSUE THREAD

**Issue by TomaszKane** [davido/gerrit-oauth-provider#19]
Hi,
is it possible to make this plug-in easy to build or better make this plugin work with any Gerrit 2.10.1 >= version?
I try to use your Release 0.1 .jar with Gerrit 2.10.2 and got "Server Error" on /login page.

Build this plugin force me to clone two repositories and resolve many dependencies of [Buck](http://facebook.github.io/buck/setup/install.html) - it's huge software/packages that I don't need on my VPS.

BTW, thanks for Release 0.1

**Comment by davido** [comment]
I agree. Sorry for not providing pre-built plugin for gerrit 2.10.2.
Due to API change plugin version 0.1 is not compatible with gerrit
2.10.2.

I will upload Release 0.2 of plugin + bundled gerrit 2.10.2 +
Hybrid OpenID/OAuth2 change next week.

**Comment by TomaszKane** [comment]
BTW if it cost some work/time maybe wait to release [Gerrit 2.11](https://gerrit.googlesource.com/gerrit/+/stable-2.11/ReleaseNotes/ReleaseNotes-2.11.txt).

**Comment by davido** [comment]
https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2
