### ISSUE TITLE
Existing OpenId accounts not linked to new Oauth identity

### ISSUE THREAD

**Issue by raags** [davido/gerrit-oauth-provider#2]
Thanks for writing this plugin, I've been able to login to my gerrit instance using google oauth. However, existing openid accounts are not being linked to the new Oauth account. Gerrit creates a new user id when I login using Oauth. I've used the following configuration :

```
[plugin "gerrit-oauth-provider-google-oauth"]
        client-id = <cid>
        client-secret = <csecret>
        link-to-existing-openid-accounts = true
```

How do I debug this? I see you've added some logging to debug these, but I don't know how to enable them. gerrit logging command is only available in 2.11rc

**Comment by davido** [comment]
Have you cherry-pciked the recent changes that are needed to enable linking of OAuth-OpenID accounts: [1]?

In patch set 2: [2] I adapted the log4j.propteries to include these lines: [3]:

```
log4j.logger.com.google.gerrit.httpd=DEBUG
log4j.logger.com.googlesource.gerrit.plugins=DEBUG
```

Also note that some prerequisites exist for the linking to work.
I explained it in this thread: [4]. Quoting it here:

Re-build and re-deploy Gerrit and plugin and perform these steps:

* remove OAuth2 account from account_external_ids table
* switch to OPENID auth scheme
* start gerrit and login with your Google's account
* observe the following log message in error_log:

```
OpenID: openid-realm=http://localhost:8080/
```

* stop gerrit, switch to OAUTH auth scheme, start gerrit, login with Google's account
* observe the following log messages in error_log:

```
GoogleOAuthService : OAuth2: canonicalWebUrl=http://localhost:8080/
GoogleOAuthService : OAuth2: scope=openid email profile
GoogleOAuthService : OAuth2: linkToExistingOpenIDAccounts=true
GoogleOAuthService : OAuth2: authorization URL=[...]scope=openid%20email%20profile&openid.realm=http%3A%2F%2Flocalhost%3A8080%2F
GoogleOAuthService : OAuth2: openid_id=https://www.google.com/accounts/o8/id?id=<*********>
OAuthSession : OAuth2: linking claimed identity to 1000000
```

According to the spec, openid_id is only provided when OpenID: openid-realm
in openid hand shake and openid.realm=http%3A%2F%2Flocalhost%3A8080%2F
in oauth2 hand shake are exactly the same and openid scope was included.


* [1] https://gerrit-review.googlesource.com/#/q/status:open+project:gerrit+branch:stable-2.10+topic:oauth-authentication-provider
* [2] https://gerrit-review.googlesource.com/#/c/66391/2
* [3] https://gerrit-review.googlesource.com/#/c/66391/2/gerrit-war/src/main/resources/log4j.properties@56
* [4] https://groups.google.com/d/topic/repo-discuss/Hjn-6BV3KBU/discussion

**Comment by raags** [comment]
I get the following error when I try to build the plugin with the new build instructions :
```
~/gerrit/gerrit-oauth-provider$ buck build plugin
Not using buckd because watchman isn't installed.
[-] PROCESSING BUCK FILES...FINISHED 0.1s
[+] BUILDING...0.7s (14/18 JOBS)
 |=> IDLE
 |=> //lib/gerrit:plugin-api__download_bin...  0.3s (running genrule[0.3s])
Download file:///home/raghu/.m2/repository/com/google/gerrit/gerrit-plugin-api/2.10-SNAPSHOT/gerrit-plugin-api-2.10-SNAPSHOT.jar
error using curl: Command '['curl', '--proxy-anyauth', '-sfo', '/home/raghu/.gerritcodereview/buck-cache/gerrit-plugin-api-2.10-SNAPSHOT.jar-686c942bc41cd8f1c9adcdc54a94bcf3e862f4af', 'file:///home/raghu/.m2/repository/com/google/gerrit/gerrit-plugin-api/2.10-SNAPSHOT/gerrit-plugin-api-2.10-SNAPSHOT.jar']' returned non-zero exit status 37
BUILD FAILED: //lib/gerrit:plugin-api__download_bin failed with exit code 1:
genrule
```

**Comment by davido** [comment]
Sure. That's because three changes are still pending for review: [1]. You would need to patch Gerrit 2.10.1, build it and deploy the plugin API in your local Maven repository. I added a comment here how to do that: [2].

Or just use release that I uploaded today morning. This release contains patched gerrit.war with bundled plugin [3]. See also the announcement on this thread: [4].

* [1] https://gerrit-review.googlesource.com/#/q/status:open+project:gerrit+branch:stable-2.10+topic:oauth-authentication-provider
* [2] https://github.com/davido/gerrit-oauth-provider/blob/master/lib/gerrit/BUCK#L3,L7
* [3] https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.1
* [4] https://groups.google.com/d/topic/repo-discuss/K2U6WcWSCaE/discussion

**Comment by raags** [comment]
Great, I got it working with your release. But the linking is still not working. I followed the steps you listed, but when I login using the OpenId auth, a new user gets created.

This is my original account in accout_external_ids :

```1000062 | raghu@helpshift.com    - https://www.google.com/accounts/o8/id?id=xxxxx
```1000062 |  username:raghu

When I use OpenId, a new account gets created 
```
1000086 | raghu@helpshift.com        - https://www.google.com/accounts/o8/id?xxxxx
```
After I switch to Oauth, the account does get linked, but to this new OpenId account 

```
1000086 | raghu@helpshift.com           |              | xxxxxxx
```

Not sure why OpenId is creating a new account. Also, if this works, do I have to follow this step for every user?

**Comment by davido** [comment]
>Not sure why OpenId is creating a new account.

That's the problem here. I think that new OpenID account is created when something was changed, like domain name or user's emai address. This basically means that all your users cannot authenticate with their existing OpenID identities or is new OpenID identity only created for your acount?

**Comment by raags** [comment]
Yes, I was using a different domain for the new server. Its fixed now, account linking is working as expected. Thanks for you help!

**Comment by tsuna** [comment]
I also had to change the domain name because Google OAuth does not support naked domains and we were hosting our Gerrit instance at http://gerrit.  Since I had to change the domain, I didn't realize that this would impact existing OpenID-created accounts.  How can I migrate existing accounts anyway?

@raags how did you solve the problem?

**Comment by davido** [comment]
In this case plugin's automatic linking doesn't work. You would need to link the users manually. Another approach would be to hack the plugin and try to guess the OpenID account based on the email address.

**Comment by tsuna** [comment]
How would I go about linking the users manually?

As far as hacking the plugin, is it just a matter of munging the `canonicalWebUrl` used in `getAuthorizationUrl()`:

```java
      if (linkToExistingOpenIDAccounts) {
        url += "&openid.realm=" + URLEncoder.encode(canonicalWebUrl,
            StandardCharsets.UTF_8.name());
      }
```

**Comment by raags** [comment]
@tsuna we have gerrit on a subdomain, so I'm just going to switch dns to the new server. I think canonicalWebUrl is not going to work, as the redirect must match with what you provide in the google developer console. Maybe you can configure another redirect on the old server, I'm not sure.

Gerrit supports manually linking the different identities  :

https://wiki.documentfoundation.org/Development/gerrit/setup#Migrating_away_from_Google_and_linking_multiple_OpenIDs

There are scripts as well, but not sure if they work : https://code.google.com/p/gerrit/wiki/SqlMergeUserAccounts
