### ISSUE TITLE
Server Error on github registration

### ISSUE THREAD

**Issue by tko** [davido/gerrit-oauth-provider#20]
We've set up the [v0.1 release](https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.1) and our team are signing up. It's mostly working alright, but in two cases they got 'Server Error' instead on $gerrithost/oauth?code=something&state=else. In error log there's this:
```
[2015-04-13 20:36:51,344] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?code=something&state=else
java.lang.NullPointerException
        at com.googlesource.gerrit.plugins.oauth.GitHubOAuthService.getUserInfo(GitHubOAuthService.java:96)
        at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:95)
        at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:119)
        at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:70)
[..and so on..]
```

Any ideas what might be happening? Why only some users and not all of them?

**Comment by davido** [comment]
Strange. It doesn't work only for the same users? Ask GitHub support?

https://github.com/davido/gerrit-oauth-provider/blob/v0.1/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java#L96

**Comment by tko** [comment]
We've got ten users registered ok, two failing. I asked them to revoke the app and try again, clear cookies, etc. but the same error persists, now waiting for GitHub support to reply. More logging would be helpful when things go sideways. Is there any way to manually replay the same request to see the response content?

**Comment by ppaperno** [comment]
I'm on same team as @tko . We now have 4 users experiencing same error.

**Comment by tko** [comment]
To answer my own question I suppose the following should help debug the issue given the `code` value in the error. The code expires in few minutes though.
```
curl -H 'Accept: application/json' -i -d '' 'https://github.com/login/oauth/access_token?code={code}&client_id={public}&client_secret={secret}'

curl -i 'https://api.github.com/user?access_token={access_token from previous command}'
```

**Comment by davido** [comment]
Can you see difference in response for user who is able to connect and user who is not?

**Comment by davido** [comment]
Added additional null-checks and logs: [1]. Can you build the plugin yourself? Or should I build it and upload for you to test?

[1] https://github.com/davido/gerrit-oauth-provider/blob/master/src/main/java/com/googlesource/gerrit/plugins/oauth/GitHubOAuthService.java#L89-L111

**Comment by davido** [comment]
New plugin release with check and verbos eoutput is here: [1].

[1] https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.3

**Comment by tko** [comment]
I haven't tried the plugin, but it seems the `user:email` scope is being dropped for the problematic user. When things work the account_token comes with `scope="user:email"`, when things fail `scope=""`

The change in scope results in some fields being _omitted_ in the response, with "user:email" scope we get `id`, `login`, `name`, `email`, when the scope is empty we only get `id`, `login` -- I don't know how JsonObject behaves but I wouldn't be surprised missing fields are (java) null rather than JsonElement. Looks like the new release addresses that already.

I can see the difference also in the output of
```
curl 'https://api.github.com/users/{username}?client_id={public}&client_secret={secret}'
```

**Comment by tko** [comment]
Using the v0.1 plugin one of the users were able to sign up after setting up a real name in github. Now the query for /users/username includes _both_ name and email fields as well, the latter being empty string though.

**Comment by davido** [comment]
Fixed in https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.3.
