### ISSUE TITLE
Sometimes I get "Not Found" on the login page

### ISSUE THREAD

**Issue by cermakcz** [davido/gerrit-oauth-provider#21]
Not sure if this is actually caused by the plugin, but if I come to gerrit after some time and need to login again, I get "Not Found" text on the login page and the only way to get it working again is to delete cookies. There's usually just one, JSESSIONID.

**Comment by cermakcz** [comment]
It also helps if whole Gerrit is restarted.

**Comment by tprochazka** [comment]
+1

**Comment by davido** [comment]
This was fixed in #5. Try release https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2.

**Comment by cermakcz** [comment]
Thanks. So if I use the 0.2 plugin and the next release of Gerrit (when it's released), it should work fine, right?

**Comment by davido** [comment]
Yes, But you don't need to wait until 2.10.3 is going to be released. I have built it with the needed patch included and uploaded release.war to https://github.com/davido/gerrit-oauth-provider/releases/tag/v0.2.

**Comment by davido** [comment]
Closing as duplicate of #5.
