### ISSUE TITLE
Add restricting sign-in to specific google apps hosted domains

### ISSUE THREAD

**Issue by bartekwojcicki** [davido/gerrit-oauth-provider#22]
It would be nice if one could specify google apps domain in gerrit.config to restict sign in.
```
[plugin "gerrit-oauth-provider-google-oauth"]
	client-id = foo
	domain = example.com
```
It would require adding hd param to authentication request and validating domain in token.
https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

**Comment by dliberman** [comment]
I second that.
... assuming it would work just the same as the parameter "openIdDomain" in the auth section, right? Cause right now it's not filtering any new accounts anymore.

**Comment by carlherbst** [comment]
+1, last element needed to mirror our previous openid setup.

**Comment by davido** [comment]
> It would require adding hd param to authentication request and validating domain in token.

[Reading the spec](https://developers.google.com/identity/protocols/OpenIDConnect#obtainuserinfo):

```
{"iss":"accounts.google.com",
 "at_hash":"HK6E_P6Dh8Y93mRNtsDB1Q",
 "email_verified":"true",
 "sub":"10769150350006150715113082367",
 "azp":"1234987819200.apps.googleusercontent.com",
 "email":"jsmith@example.com",
 "aud":"1234987819200.apps.googleusercontent.com",
 "iat":1353601026,
 "exp":1353604926,
 "hd":"example.com" }
```

Given the description:

```
hd		The hosted Google Apps domain of the user. Provided only if the user belongs to a hosted domain.
```

I wonder if this really need to be checked? I cannot really test it, as I don't have hosted domain, but adding `&hd=example.com` to authorization URL already restricts the ability to login to only this domain. I was unable to login and to get response with `JWT` token at all.

IOW, I wonder if this diff already solved it: [1]. Can someone give it a try?

[1] http://paste.openstack.org/show/206526/

**Comment by carlherbst** [comment]
Oh interesting, I'll give it a shot next week and report back.

**Comment by davido** [comment]
Thx. don't forget to add `domain` option to th config file:

```
[plugin "gerrit-oauth-provider-google-oauth"]
    client-id = foo
    domain = example.com
```

**Comment by carlherbst** [comment]
Should I need to add anything besides domain parameter in the config?

I see the hd = ourdomain.net in the request, which isn't present during normal google account sign ins, but they're still able to sign in.

Using gerrit 2.11 and latest release.

**Comment by davido** [comment]
You applied the diff and built new plugin version and deploy it? They were able to sign in with ``theirdomain.net`, even though `hd = ourdomain.net` was included in request? Strange. I wasn't able to sign it at all, when i configure 'hd = example.com'. But may be that's because I wasn't able to sign in with example.com. And this is different when it's possible? Anyway, that's probably why `hd`must be checked in the token response, according to the spec.

**Comment by carlherbst** [comment]
Ah didn't realize that diff wasn't merged in already.  I just applied it and rebuilt the plugin, regular google domains are indeed being blocked, only our google apps domain are making it past the login screen, that did it!

When trying to login with a disallowed domain there isn't any warning message or indication why they can't pass the login screen, but that's not much of a concern for us.

Thanks for the support.

**Comment by the4yeast** [comment]
Hi @carlherbst 

Is there any reason you didn't submit a pull request?
I'm also interested in that same feature and I'm curious if anything is actually preventing you from making your work official.

**Comment by davido** [comment]
Well, he only applied my diff: [1]. I was buys with other stuff and will merge this later.

[1] http://paste.openstack.org/show/206526/

**Comment by the4yeast** [comment]
Sounds great, thanks.

**Comment by davido** [comment]
So I re-read the spec again and realized, that ID token must be checked to prevent client side manipulation, https://developers.google.com/identity/protocols/OpenIDConnect#authuser:

```
The hd (hosted domain) parameter streamlines the login process
for Google Apps hosted accounts. By including the domain of the
user (for example, mycollege.edu), you restrict sign-in to accounts
at that domain. For Google Apps customers that have SAML set up
with their own authentication infrastructure, the hd parameter
automatically redirects to that user's SAML resource to log in.

To protect against client-side request modification, be sure to validate
that the returned ID token has a matching hd claim (which is proof the
account does belong to the hosted domain).
```

So my previous diff was wrong. Here is the correct implementation: [1].
Can someone give it a try? I cannot really test it.

[1] http://ostrovsky.org/gerrit/0001-Add-support-for-hosted-domain-to-Google-OAuth-provid.patch

**Comment by the4yeast** [comment]
@davido I've just tried it, with and without client-side request modification - worked well for me!

**Comment by i-chess** [comment]
I just tried it with a new setup. I installed gerrit , and it didn't work.
I install gerrit 2.11.1 with plugin downloaded from here
https://github.com/davido/gerrit-oauth-provider/releases/download/v2.11/gerrit-oauth-provider.jar

and my configuration looks like :
[gerrit2@CentOS-70-64-minimal ichess]$ cat ~/ichess_il/etc/gerrit.config 
...
[auth]
        type = OAUTH
[plugin "gerrit-oauth-provider-google-oauth"]
        client-id = 472107181923.apps.googleusercontent.com
        domain = ichess.co.il

still, it allows anyone to login, not just members of ichess.co.il domain
did I miss anything ?

**Comment by davido** [comment]
> did I miss anything ?

Yes: #37.

**Comment by i-chess** [comment]
Thanks alot. working now !
I'd appreciate if you can attend issue 
https://github.com/davido/gerrit-oauth-provider/issues/38
