### ISSUE TITLE
Sign in not found

### ISSUE THREAD

**Issue by loboolsson** [davido/gerrit-oauth-provider#25]
Around the 24 hour mark the sign in stops working. Clicking "Sign in" does not initialize a google login. It leads to the URL http://domain.com/login/%23%2Fq%2Fstatus%3Aopen and shows the message "Not Found" on screen. No error output is shown in error_log or httpd_log. The request itself with GET protocol, timestamp ip-address and so on is correcly logged in httpd_log but thats it

I have not configured a Github login.

A restart of gerrit (./gerrit.sh restart) solves the problem every time

**Comment by davido** [comment]
Closing as duplicate of #5.
