### ISSUE TITLE
OAuth users cannot see any Gerrit group

### ISSUE THREAD

**Issue by dmikurube** [davido/gerrit-oauth-provider#27]
I installed the plugin on Gerrit 2.11, and created a new user through OAuth. At that time, even if I added the user to an Administrator group, the user doesn't behave as an Administrator. "People" -> "List Groups" shows nothing for that user.

I'm not sure whether this issue is on Gerrit-side or on plugin-side, but please let me just report it...

----

Some additional tries:

I directly manipulated the table "account_external_ids" in Gerrit's internal DB. I added a new row with an OAuth external_id to an existing Administrator user, the user doesn't work as an Administrator. Once I removed the row, the user got back as an Administrator.

**Comment by dmikurube** [comment]
In other words, if a user has an identify of OAuth, the user is considered belonging to no any groups even if the internal DB has an entry of group status. Once the OAuth identity is removed, the user is handled as a member of the group.

**Comment by davido** [comment]
Have you checked #4 and suggested solution?

**Comment by dmikurube** [comment]
Ah, that is the root cause! Thank you very much. It fixed. I wasn't aware of the issue as the title was not about groups...

**Comment by davido** [comment]
There is also FAQ out there: https://github.com/davido/gerrit-oauth-provider/wiki/FAQ.
