### ISSUE TITLE
MIssing class error

### ISSUE THREAD

**Issue by brianmay** [davido/gerrit-oauth-provider#28]
Hello,

I built gerrit-oauth-provider and installed in my plugins directory as documented, however I can't configure it:

```
WARN: Failed to run InitStep from plugin gerrit-oauth-provider.jar (Missing class: com/google/gerrit/pgm/init/InitStep)
No plugins found with init steps.

WARN: Failed to run InitStep from plugin gerrit-oauth-provider.jar (Missing class: com/google/gerrit/pgm/init/InitStep)
Initialized /home/gerrit2/review_site
```

Have I done something wrong?

Thanks

**Comment by brianmay** [comment]
Frogot to mention, This is with gerrit 2.11

**Comment by brianmay** [comment]
Looks like something wrong with my build. I found the pre-built version, and it works.

Have you considered updating the documentation to indicate that there is a pre-built version available?

**Comment by davido** [comment]
What went wrong in your build? If you use gerrit 2.11 you need plugin from `master`. When you are building for 2.10 you need `stable-2.10` branch. I mentioned all these details in FAQ. I expect that everyone read it before reporting issues.

**Comment by brianmay** [comment]
I didn't see the FAQ until after sometime afterwards, as I was following the instructions from README.md which doesn't have any direct references to the FAQ.

I would suggest adding a link to the FAQ from README.md. Even better, why not copy the relevant questions into README.md as part of the standard install instructions?

**Comment by davido** [comment]
I wanted to keep the `README.md` as short as possible. But I see, how it's important to add some links there. Doing this right now. Thanks for the suggestions.

**Comment by davido** [comment]
Done: https://github.com/davido/gerrit-oauth-provider/blob/master/README.md
