### ISSUE TITLE
identity is untrusted

### ISSUE THREAD

**Issue by brianmay** [davido/gerrit-oauth-provider#29]
Hello,

When I log in with Google using oauth, I get what appears to be the untrusted identity issue, similar to #4 and #27.

I have tried following the instructions in the FAQ by adding the following to gerrit.config:

```
[oauth]
trustedOpenID=^.*$
```

However, that doesn't appear to help.

Any ideas?

Thanks.

**Comment by BrandonSmith** [comment]
Faced the same issue. (Looks like we're both upgrading to Google OAuth).

I dove into Gerrit source and it looks like the FAQ has an error. The key and value should be under the "auth" block:

    [auth]
        trustedOpenID = ^.*$

**Comment by davido** [comment]
Indeed. Fixed. Thanks for reporting.

**Comment by brianmay** [comment]
Just confirming, yes, that was my problem. Thanks.
