### ISSUE TITLE
Redirect url login

### ISSUE THREAD

**Issue by lyhoanglong** [davido/gerrit-oauth-provider#30]
when login with this plugin i had a error

'''

That’s an error.
Error: redirect_uri_mismatch

Application: Gerrit

You can email the developer of this application at:

The redirect URI in the request: http://domain/oauth did not match a registered redirect URI.
'''

what's I wrong? 
Do you have any suggestion @davido ?

I guest I have to add redirect url into gerrit.config something like:

[plugin "gerrit-oauth-provider-google-oauth"]
       redirect-url = 

 am I wrong?

**Comment by davido** [comment]
>I guest I have to add redirect url into gerrit.config

Nope. It's already there and called: `gerrit.canonicalWebUrl`.

Plugin fetch this option and add `/oauth` suffix and ths is exactly what you should regiter as redirect URL on OAuth provider page.
