### ISSUE TITLE
Google Oauth doesn't remember account, need to relogin everyday

### ISSUE THREAD

**Issue by raags** [davido/gerrit-oauth-provider#34]
Gerrit doesn't seem to remember the user once Oauth login is completed. The user has to redo the registration step roughly after every 24 hours, i.e. allow gerrit to access the Google Credentials. Isn't this step only required once?

Here is the relevant auth configuration I'm using :

```
[auth]
        type = OAUTH
        maxOpenIdSessionAge = 31536000
[plugin "gerrit-oauth-provider-google-oauth"]
        client-id = xxxxxx
        link-to-existing-openid-accounts = true
```

**Comment by davido** [comment]
No, web session timeout time is per default 24 hours. See discussion on #5. You can change this setting with:

```
[cache "web_sessions"]
        maxAge = 1 month
```

**Comment by raags** [comment]
Got it, thanks! I thought this was related to Oauth.
