### ISSUE TITLE
Hosted domain check not included in latest release

### ISSUE THREAD

**Issue by vances** [davido/gerrit-oauth-provider#37]
It would be great if you could create a new release which includes this important new feature.

**Comment by davido** [comment]
Note that you can pull the right version of the plugin from Gerritforge CI server: [1].

* [1] https://ci.gerritforge.com/job/Plugin_gerrit-oauth-provider_master/9/

**Comment by vances** [comment]
On Wed, Jul 8, 2015 at 2:18 PM, David Ostrovsky
<notifications@github.com> wrote:
> Note that you can pull the right version of the plugin from Gerritforge CI server: [1].

That is indeed helpful information.  Thanks!

-- 
     -Vance

**Comment by vances** [comment]
David,

Unfortunately the Gerritforge CI server no longer includes your project.  :(


On Wed, Jul 8, 2015 at 2:18 PM, David Ostrovsky
<notifications@github.com> wrote:
>
> Note that you can pull the right version of the plugin from Gerritforge CI server: [1].
>
> [1] https://ci.gerritforge.com/job/Plugin_gerrit-oauth-provider_master/9/





-- 
     -Vance

**Comment by davido** [comment]
https://github.com/davido/gerrit-oauth-provider/releases/tag/v2.11.3
