### ISSUE TITLE
identity is untrusted

### ISSUE THREAD

**Issue by ntfreak** [davido/gerrit-oauth-provider#4]
Firstly thanks for your work on this, we have quite a few users on our project gerrit server (review.openocd.org) that we need to migrate from the old google OpenID.

I have built gerrit 2.10.1 and applied the following patches - 66310/1, 66311/2, 66312/3 and 66313/2.
Instructions were taken from here - https://groups.google.com/forum/#!topic/repo-discuss/SQdmidojZFQ

When i add/link any google account it gets marked as an untrusted identity, and as such looses all groups except "Anonymous Users" and "Registered Users". When debugging the problem I noticed that the identity is only untrusted when using auth.type OPENID. If i switch to OAUTH all is ok and the users groups are restored.

I know that auth.trustedOpenID would make this work, but what would I need to enter?

We were also planning on changing our server domain name, guessing this would make the account linking from the old google openid to oauth2 fail?

Cheers

**Comment by rolandschulz** [comment]
I set it trustedOpenID=^.*$ to fix it.

**Comment by ntfreak** [comment]
Many Thanks.
