### ISSUE TITLE
Gerrit's page hangs while trying to do "Sing In"

### ISSUE THREAD

**Issue by ruslo** [davido/gerrit-oauth-provider#40]
Hi,

I'm trying to start a gerrit instance with this plugin but when auth.type set to OAUTH I can't register new user since browser hangs (it keep loading page with "Waiting for testgerrit.example.com...") every time I click on "Sign In".

Here is the script I'm using on my testing machine:

``` bash
#!/bin/bash -e

set -x

/var/lib/gerrit/bin/gerrit.sh stop --site-path /var/lib/gerrit || echo ""

rm -rf /var/lib/gerrit

mkdir -p /var/lib/gerrit/plugins
mkdir -p /var/lib/gerrit/etc

wget --directory-prefix /var/lib/gerrit https://gerrit-releases.storage.googleapis.com/gerrit-2.11.war
wget --directory-prefix /var/lib/gerrit/plugins https://github.com/davido/gerrit-oauth-provider/releases/download/v2.11/gerrit-oauth-provider.jar

cp /home/gerrit.config /var/lib/gerrit/etc/gerrit.config

java -jar /var/lib/gerrit/gerrit-2.11.war init --batch -d /var/lib/gerrit
java -jar /var/lib/gerrit/gerrit-2.11.war reindex -d /var/lib/gerrit

/var/lib/gerrit/bin/gerrit.sh start --site-path /var/lib/gerrit
```

I've tried both google and github. Result is the same.

Here is a configuration I have after `java -jar ... init`:

```
> cat /var/lib/gerrit/etc/gerrit.config
[gerrit]
  basePath = git
  canonicalWebUrl = http://testgerrit.example.com/
[database]
  type = h2
  database = db/ReviewDB
[index]
  type = LUCENE
[auth]
  type = OAUTH
[sendemail]
  smtpServer = localhost
[container]
  user = root
  javaHome = /usr/lib/jvm/java-7-openjdk-amd64/jre
[sshd]
  listenAddress = *:29418
[httpd]
  listenUrl = http://*:80/
[cache]
  directory = cache
[plugin "gerrit-oauth-provider-google-oauth"]
  client-id = 37xxxxx6c.apps.googleusercontent.com
  client-secret = 7qxxxxxjK
  link-to-existing-openid-accounts = true
```

Thanks, Ruslan

**Comment by ruslo** [comment]
Okay, I've waited patiently for the result and it looks like everything works but every time I restart gerrit instance I have to wait about > 1 hours to `Sign In`. It is intentioned behaviour? Or may be I'm missing something?

**Comment by davido** [comment]
Of course not. You are the first one, who is reporting that. Not sure, what is the root cause.

**Comment by ruslo** [comment]
Is there a way to debug this somehow? All gerrit logs looks good now so they are quite useless.

**Comment by davido** [comment]
Sure: [1].

[1] https://github.com/gerrit-review/gerrit/blob/master/Documentation/dev-eclipse.txt

**Comment by ruslo** [comment]
> Sure

Just to clarify things I'm not a gerrit developer, I'm just a user. By `Is there a way to debug this somehow?` I mean I can set some environment variable or some settings like `gerrit-oauth-provider.debug = on` and paste extra logs here so you can say what is wrong with your plugin/gerrit or google/github.

Also you may look at the script above and let me know if there are any issues in it.

Thanks, Ruslan

**Comment by davido** [comment]
Can you try OpenID instead? Does it work for you? Note, that i cannot troubleshoot this problem for you. You may also want to ask help on developer mailing list of Gerrit project.

**Comment by ruslo** [comment]
> Can you try OpenID instead? Does it work for you?

Work like a charm. Just 's,OAUTH,OPENID,' and run same script.

> You may also want to ask help on developer mailing list of Gerrit project.

So what should I ask there? Gerrit works fine, I'm turning plugin ON and have problems. After 1 hours of delay after restart OAUTH works - so I guess it's not a google/github issue too.

> Note, that i cannot troubleshoot this problem for you.

Feel free to close this issue if you're not interest in further investigation.

Thanks, Ruslan

**Comment by davido** [comment]
Have you tried to open network activity page in your browser and investigate which request hangs?

**Comment by ruslo** [comment]
> Which OpenID provider did you use?

Yahoo. Google doesn't work (that's the reason I'm trying to use OAUTH).

> Have you tried to open network activity page in your browser and investigate which request hangs?

```
Request URL: http://testgerrit.<example.com>/login/#/q/status:open
Request method: GET
```

**Comment by davido** [comment]
You mean that OAuth handshake and auth phase was successful? And that after it the first request hangs? What happens when you refresh the page with Ctrl+R?

**Comment by ruslo** [comment]
> You mean that OAuth handshake and auth phase was successful?

Don't know. See no other packages. First request is GET, that's all. Just for your information I'm using Firefox, Developer -> Network tool. I can install Wireshark if it helps.

> What happens when you refresh the page with Ctrl+R?

Start page opened (same as http://testgerrit.<example.com>/). Then I hit "Sign In" and it hangs again.

**Comment by t3hpr1m3** [comment]
I can add a second to this issue.  Fresh OS install, fresh Gerrit.  Only this plugin installed.  Takes ~1 hour for logins to respond.  I did some additional research, and it would appear that the login is hanging because the /oauth route also hangs.  After that initial hour or so, logins via Github work flawlessly.  Short of firing up eclipse, is there anything I can do to help track this down?  I can try to get a dev environment up for this, but Gerrit is running on a VM server in the DC.

**Comment by duchy** [comment]
I also encountered this issue (github oauth) each time the Gerrit service is restarted.
Any progress on this issue?
Really bad experience ...:(

**Comment by davido** [comment]
Unfortunately, I'm not able to reproduce it, so no progress.

**Comment by andros5000** [comment]
Hello david,

Is there anyway to set a longer timeout on Google Auth then what it currently is now?

**Comment by davido** [comment]
The answer was given in this issue: https://github.com/davido/gerrit-oauth-provider/issues/5

**Comment by sokolovstas** [comment]
@davido Hi! I have same issue on fresh install of gerrit and plugin. I don't wait a hour, but if it works hour ago I will comment here.

**Comment by sokolovstas** [comment]
Yes login page opened fine after 15 minutes.

**Comment by thompatry** [comment]
I have the same issue here. It hangs and nothing happens. Brand new install.

**Comment by easybe** [comment]
I am experiencing the same behaviour here. I am using  openfrontier/docker-gerrit:latest (Gerrit 2.12.5) and gerrit-oauth-provider 2.13.1. The first login hangs forever. When I reload Gerrit's front page I am logged in though. My OAuth related Docker container settings are following:

    AUTH_TYPE=OAUTH
    OAUTH_ALLOW_EDIT_FULL_NAME=true
    OAUTH_ALLOW_REGISTER_NEW_EMAIL=true
    OAUTH_GOOGLE_RESTRICT_DOMAIN=example.com
    OAUTH_GOOGLE_CLIENT_ID=...
    OAUTH_GOOGLE_CLIENT_SECRET=...

I do see following exception in the log:

    java.lang.StringIndexOutOfBoundsException: String index out of range: -1
     	at java.lang.String.substring(String.java:1931)
     	at com.google.gerrit.httpd.auth.oauth.OAuthSession.authenticateAndRedirect(OAuthSession.java:153)
     	at com.google.gerrit.httpd.auth.oauth.OAuthSession.login(OAuthSession.java:104)
     	at com.google.gerrit.httpd.auth.oauth.OAuthWebFilter.doFilter(OAuthWebFilter.java:109)
     	at com.google.gwtexpui.server.CacheControlFilter.doFilter(CacheControlFilter.java:73)
     	at com.google.gerrit.httpd.RunAsFilter.doFilter(RunAsFilter.java:117)
     	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy$1.doFilter(AllRequestFilter.java:136)
     	at com.google.gerrit.httpd.AllRequestFilter$FilterProxy.doFilter(AllRequestFilter.java:105)
     	at com.google.gerrit.httpd.RequestContextFilter.doFilter(RequestContextFilter.java:75)
     	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119)
     	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133)
     	at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130)
     	at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203)
     	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130)
     	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
     	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
     	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
     	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
     	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
     	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
     	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
     	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
     	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
     	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95)
     	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
     	at org.eclipse.jetty.server.Server.handle(Server.java:499)
     	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
     	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
     	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
     	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
     	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
     	at java.lang.Thread.run(Thread.java:745)
    [2016-10-03 09:01:43,482] [HTTP-64] ERROR com.google.gerrit.pgm.http.jetty.HiddenErrorHandler : Error in GET /oauth?state=...&authuser=1&hd=peach.info&session_state=...&prompt=none

Any ideas?

**Comment by davido** [comment]
I don't have currently access to my machine, so just guessing: something seems to be wrong with redirect token, that is set here: [1] and accessed here: [2].

[1] https://github.com/GerritCodeReview/gerrit/blob/stable-2.12/gerrit-oauth/src/main/java/com/google/gerrit/httpd/auth/oauth/OAuthSession.java#L118-L119
[2] https://github.com/GerritCodeReview/gerrit/blob/stable-2.12/gerrit-oauth/src/main/java/com/google/gerrit/httpd/auth/oauth/OAuthSession.java#L153-L154

**Comment by easybe** [comment]
Thanx for getting back to me. Actually, I am not sure what caused the above exception. Probably something else, because it no longer appears.

Still, the issue remains. I am using NGINX as a reverse proxy, but I have experienced the same behaviour when directly accessing Gerrit. I've managed to make my log more verbose. Here's what I see when trying to sign in:

    nginx          | x.x.x.x - - [17/Oct/2016:11:19:55 +0000] "GET /login/%23%2Fq%2Fstatus%3Aopen HTTP/1.1" 504 183 "http://scm.example.com/" ...
    nginx          | 2016/10/17 11:19:55 [error] 5#5: *20 upstream timed out (110: Operation timed out) while reading response header from upstream, client: x.x.x.x, server: scm.example.com, request: "GET /login/%23%2Fq%2Fstatus%3Aopen HTTP/1.1", upstream: "http://172.18.0.3:8080/login/%23%2Fq%2Fstatus%3Aopen", host: "scm.example.com", referrer: "http://scm.example.com/"

NGINX times out after 60s, but then something happens:

    gerrit         | [2016-10-17 11:20:08,122] [HTTP-65] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:20:08,124] [HTTP-64] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:20:08,125] [HTTP-64] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login-PHASE1 OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:20:08,127] [HTTP-64] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: authorization URL=https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=...apps.googleusercontent.com&redirect_uri=http%3A%2F%2Fscm.example.com%2Foauth&scope=openid%20email%20profile&openid.realm=http%3A%2F%2Fscm.example.com%2F&hd=example.com
    gerrit         | [2016-10-17 11:20:08,128] [HTTP-65] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login-PHASE1 OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:20:08,129] [HTTP-65] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: authorization URL=https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=...apps.googleusercontent.com&redirect_uri=http%3A%2F%2Fscm.example.com%2Foauth&scope=openid%20email%20profile&openid.realm=http%3A%2F%2Fscm.example.com%2F&hd=example.com

The second try is successfull:

    gerrit         | [2016-10-17 11:28:09,194] [HTTP-63] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:28:09,198] [HTTP-63] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login-PHASE1 OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:28:09,209] [HTTP-63] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: authorization URL=https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=...apps.googleusercontent.com&redirect_uri=http%3A%2F%2Fscm.example.com%2Foauth&scope=openid%20email%20profile&openid.realm=http%3A%2F%2Fscm.example.com%2F&hd=example.com
    gerrit         | [2016-10-17 11:28:09,724] [HTTP-64] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login OAuthSession [token=null, user=null]
    gerrit         | [2016-10-17 11:28:09,724] [HTTP-64] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login-Retrieve-User OAuthSession [token=null, user=null]

    nginx          | x.x.x.x - - [17/Oct/2016:11:28:09 +0000] "GET /login/%23%2Fq%2Fstatus%3Aopen HTTP/1.1" 302 0 "http://scm.example.com/" ...

    gerrit         | [2016-10-17 11:28:11,119] [HTTP-64] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : User info response: {
                         ...
    gerrit         | }
    gerrit         |
    gerrit         | [2016-10-17 11:28:11,122] [HTTP-64] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: openid_id=http://example.com/openid?id=...
    gerrit         | [2016-10-17 11:28:11,122] [HTTP-64] DEBUG com.googlesource.gerrit.plugins.oauth.GoogleOAuthService : OAuth2: hd=example.com
    gerrit         | [2016-10-17 11:28:11,123] [HTTP-64] DEBUG com.google.gerrit.httpd.auth.oauth.OAuthSession : Login-SUCCESS OAuthSession [token=com.google.gerrit.extensions.auth.oauth.OAuthToken@226e91df, user=com.google.gerrit.extensions.auth.oauth.OAuthUserInfo@7a863ad8]

    nginx          | x.x.x.x - - [17/Oct/2016:11:28:11 +0000] "GET /oauth?state=...&authuser=0&hd=example.com&session_state=...&prompt=none HTTP/1.1" 302 0 "http://scm.example.com/" ...

Any idea what is so much time here? 60s+ is definitely too long. Often, signing in is impossible because it hangs forever. I find it hard to believe that Google is the problem here...

**Comment by davido** [comment]
TBH, I have no idea. I was never able to reproduce it. I would try to take nginx out of picture, and would try to repoduce it with naked gerrit and povide as mich information as possible, if not to say to set up deverlopment environment and try to track it down on your side.

**Comment by noroutine** [comment]
The root cause for me was slow RNG on digitalocean, solved by following https://www.digitalocean.com/community/tutorials/how-to-setup-additional-entropy-for-cloud-servers-using-haveged

HTH

**Comment by davido** [comment]
Thanks for letting us know. We should mention it on Wiki page as known issue.

**Comment by mwebber** [comment]
For an alternative view of this, read https://www.2uo.de/myths-about-urandom/.

There, the author claims that it's ok to use `/dev/urandom` (which is non-blocking) for cryptographic purposes, and is actually preferred to `/dev/random` (which is blocking, can causes this problem).

If that is true, we should switch to using `/dev/urandom`, which would solve this problem (Gerrit hanging on sign-in when using the OAuth plugin).

I'l have a poke around and see if I can find any other write-ups about this.
