### ISSUE TITLE
Any chances for relase based on Gerrit 2.11.2 ?

### ISSUE THREAD

**Issue by TomaszKane** [davido/gerrit-oauth-provider#42]
Hi,
Both [2.11.1](https://gerrit-documentation.storage.googleapis.com/ReleaseNotes/ReleaseNotes-2.11.1.html) and [2.11.2](https://gerrit-documentation.storage.googleapis.com/ReleaseNotes/ReleaseNotes-2.11.2.html) has significant changes/fixes.

**Comment by davido** [comment]
>Both 2.11.1 and 2.11.2 has significant changes/fixes.

I know, but none of these changes/fixes touched OAuth extension point, right? Unless I'm missing something you should be fine with the latest available artifact from gerritforge CI. Link was publised in #37.

**Comment by TomaszKane** [comment]
OK, thanks, work great with 2.11.2
