### ISSUE TITLE
unable to build on Ubuntu-14.04

### ISSUE THREAD

**Issue by YSantoshReddy** [davido/gerrit-oauth-provider#59]
![selection_002](https://cloud.githubusercontent.com/assets/17761320/15322217/09141f7a-1c59-11e6-923c-53b312a54d00.png)

**Comment by davido** [comment]
This is line 174 in `download_file.py`:

```
   check_call(['zip', '-d', args.o] + exclude)
``´

So installing `zip` utility on your system should fix it.

**Comment by YSantoshReddy** [comment]
Thanks for the quick reply and it was helpfull
