### ISSUE TITLE
Name of .jar in release

### ISSUE THREAD

**Issue by CoRfr** [davido/gerrit-oauth-provider#74]
Hi David,

There is a docker image (https://github.com/openfrontier/docker-gerrit.git) that uses your plugin, and it tries to download releases from your plugin, with an URL like:
https://github.com/davido/gerrit-oauth-provider/releases/download/v${GERRIT_VERSION}/gerrit-oauth-provider.jar

It seems that before 2.13.1 (included) that was good, but on 2.13.2 the jar name is 'gerrit-oauth-provider-92940e6.jar', is this a change of convention or just a mistake ?

Thanks
CoR

**Comment by CoRfr** [comment]
Oh BTW since you're using travis it would also be possible to upload releases from there when you tag: https://docs.travis-ci.com/user/deployment/releases/

**Comment by davido** [comment]
You never know, what user do with your artifacts ;-)
Let me rename it back...

**Comment by davido** [comment]
Done.

**Comment by davido** [comment]
| Oh BTW since you're using travis it would also be possible to upload releases from there when you tag: https://docs.travis-ci.com/user/deployment/releases/

Thanks, there is even `deploy.on` condition, so I could check if version name doesn't contains `-SNAPSHOT` it shouldn't upload a release.
