### ISSUE TITLE
oauth redirect to 127.0.0.1 after login

### ISSUE THREAD

**Issue by jbardin** [davido/gerrit-oauth-provider#8]
I'm using the gerrit 2.10.1 and plugin release provided here.

Github oauth works correctly, and redirects back to the correct callback url.
After the callback is processed, the client is redirected to https://127.0.0.1:8444/... 

canonicalWebUrl is correctly set, and works for other links.

**Comment by tko** [comment]
This may be reverse proxy misconfiguration, see https://gerrit.litl.com/Documentation/config-reverseproxy.html

**Comment by jbardin** [comment]
Thanks @tko, I totally missed that in the rush to setup authentiation.
