### ISSUE TITLE
Register new email button missing

### ISSUE THREAD

**Issue by PhilipStefanov** [davido/gerrit-oauth-provider#83]
After moving from LDAP to gerrit-oauth-provider Settings -> Contact information -> Register new email button is missing.
Is this intended by the plugin design or some Gerrit restriction?
I was planning to add the mail directly into the database...

**Comment by davido** [comment]
This is controlled by its own setting and was added in this change upstream: [1].

```
  [oauth]
      allowRegisterNewEmail = true
```

* https://gerrit-review.googlesource.com/74441
