### ISSUE TITLE
Full name shows "???" instead of my real name Google passed

### ISSUE THREAD

**Issue by Dry8r3aD** [davido/gerrit-oauth-provider#86]
== Issue ==
I am a korean user, and obviously, my Google account name is in korean.
which is 2 bytes, unlike english, which is 1 byte per letter. (maybe this could be a problem :\ )

When i login in with Google SSO(using this plugin), my real name appears like "???" instean of my real name ("윤건영").

== What I have checked ==
1. gerrit/plugin debug log
- Yes, I checked the parsed datas in json, and Google gave right information as below. As you can see, they did not send "???" to gerrit server.
```
"name": "윤건영",
 "given_name": "건영",
 "family_name": "윤",
```

2. database check
- I manually changed my full_name from "???" to "윤건영" and it did work, but as soon as i re-login, full_name is changed back to "???"
- So i guess this information is re-newed when i login :\

== Env ==
- Gerrit v2.13.7 (Newest stable)
- Plugin v2.13.6 ( yes i am aware that it does not match with gerrit but this was the newest i could find)

== To reproduce ==
- use an account which has korean name (or 2~3 byte like chinese, etc), and login
   -  FYI, korean is 3 byte per letter in UTF-8

**Comment by Dry8r3aD** [comment]
and this did not happend in 2.11 for yout information.

thank you

**Comment by davido** [comment]
That is strange. I tested it with hebrew, and t works as expected.
Correct name is shown: [1] Can you debug it?

* [1] http://imgur.com/a/g9fYY

**Comment by Dry8r3aD** [comment]
I inserted some logs for debugging, and i found out that it's not plugin's problem, but gerrit core's problem.

I will open another case to gerrit project. 

thank you for looking into this issue.
