### ISSUE TITLE
username set to email address

### ISSUE THREAD

**Issue by fstefanov** [davido/gerrit-oauth-provider#89]
With gerrit 2.13.6 after creating new user the username field is blank which is ok.
After an upgrade to gerrit 2.13.7 now username is filled with user email address.

**Comment by davido** [comment]
What OAuth provider are you using?

**Comment by PhilipStefanov** [comment]
facebook

**Comment by davido** [comment]
For Facebook provider, email is used for username. See

https://gerrit.googlesource.com/plugins/oauth/+/master/src/main/java/com/googlesource/gerrit/plugins/oauth/FacebookOAuthService.java#111

```java
      JsonElement email = jsonObject.get("email");
      // Heads up!
      // Lets keep `login` equal to `email`, since `username` field is
      // deprecated for Facebook API versions v2.0 and higher
      JsonElement login = jsonObject.get("email");
```

If you like different behavior here, probably the way to go to make this configurable, like this is the case for Google OAuth provider:

```java
  static final String USE_EMAIL_AS_USERNAME = "use-email-as-username";
  this.useEmailAsUsername = cfg.getBoolean(
        InitOAuth.USE_EMAIL_AS_USERNAME, false);
```

**Comment by fstefanov** [comment]
Finally managed to build it!
Thank you for your help Davido I haven't build Gerrit since 2.13
Documentation is poor indeed...

**Comment by davido** [comment]
Great.
