### ISSUE TITLE
Cannot link to user identity with OAuth prefix after upgrade to 2.13.6

### ISSUE THREAD

**Issue by nwoodward** [davido/gerrit-oauth-provider#91]
I just upgraded Gerrit from 2.13.5 to 2.13.6, as well as the oauth-provider plugin to the same version. I ran the same init (with fix-legacy-user-id set to true) and reindex commands as always, removed everything in /cache, and restarted Gerrit. Now when I try to log in using Google I get 403 Forbidden. The logs look like this:
```
[2017-06-28 09:56:28,926] [HTTP-69] INFO  com.google.gerrit.httpd.auth.oauth.OAuthSession : OAuth2: linking claimed identity to [USER_ID]
[2017-06-28 09:56:28,932] [HTTP-69] ERROR com.google.gerrit.httpd.auth.oauth.OAuthSession : Cannot link: google-oauth:[GOOGLE_ID] to user identity:
  Claimed ID: [USER_ID] is [GOOGLE_ID]
```
I cleared my browser cache, but got the same results. I can't tell why the claimed ID doesn't contain the "google-oauth:" prefix. I don't know if the reindex didn't actually update something or if when I try to log in my browser is still sending the id without the prefix. 

Has anyone experienced this behavior after upgrading to 2.13.6?

**Comment by davido** [comment]
See the announcement on the mailing list (repo-discuss), and another bug: All versions older than 2.13.7 are broken. You need to use at least 2.13.7, but to be honest, alwas try to use the latest available version. 2.13.8 and 2.13.9 is going to be released in the next days.

**Comment by davido** [comment]
Can you confirm, that upgrading to most recent available 2.13 version and running the reindex after the upgrade fixed this problem?

**Comment by nwoodward** [comment]
I was on version 2.13.8 when I had these authentication problems, but upgrading to 2.14 (and reindexing) resolved the issue. Thanks for your help.

**Comment by davido** [comment]
Thanks for confirming, closing this issue.
