### ISSUE TITLE
Canonical url is not callback url

### ISSUE THREAD

**Issue by dozd** [davido/gerrit-oauth-provider#95]
Hello,

I have my gerrit installation behind nginx ssl proxy under docker. While `canonicalWebUrl` is like http://\*gerit\*:8080/ i want to have different callback url for oauth (https://\*gerrit\*/oath).

I would suggest to add new cfg `callback-url` that can be set for providing different url than `canonicalWebUrl `.

Can propose a PR if agreed.

**Comment by mwebber** [comment]
`canonicalWebUrl` is supposed to be the URL that the external world uses to get to Gerrit.

For the OAuth callback address (which you configure at in the OAuth provider), Gerrit uses the fixed value of `<canonicalWebUrl>/oauth`.

If you're behind nginx ssl, I would have expected something like:
`canonicalWebUrl = https://gerrit.your.domain/` (note: http**s**, and no port)
`httpd.listenUrl = proxy-https://*:8080/`
In that case, 8080 is the local port which Gerrit listens on. Nobody uses that directly, instead all requests come via https Nginx.

So, I don't understand your configuration, and what you are trying to achieve. Can you provide some more detail? Thanks

**Comment by dozd** [comment]
You're right. I forgot `httpd.listenUrl`. Your expectation about my configuraiton should be my configuration in the first place :-). Thank.
