### ISSUE TITLE
Inconsistent github provisioning

### ISSUE THREAD

**Issue by kallisti5** [davido/gerrit-oauth-provider#96]
Here is an example via admin-console ls-users:

All of these have been provisioned via github oauth.
```
XXX0 | jdoe | Jane Doe | jdoe@jane.com | active
XXX1 | jdoe2 | Jane Doe2 | jdoe2@jane.com | active
XXX2 | jdoe3 | Jane Doe3 | jdoe3@jane.com | active
XXX3 | jdoe4 | jdoe4 | | active
XXX4 | jdoe5 | jdoe5 | | active
XXX5 | jdoe6 | Jane Doe6 | jdoe6@jane.com | active
```

XXX3 and XXX4   seem to be provisioned oddly with no email and the username in the name field. Any ideas what causes this?

No errors in logs.

**Comment by davido** [comment]
Works as expected. Email is optional in GH's user account. Check my account, no email exposed.

**Comment by kallisti5** [comment]
Yeah, so the GH users seeing this didn't have a public email.  Is there any way to correct this issue?

- User enables a public email address, and signs in again. The email shows up in contact information ,but they are unable to save new preferred email with error: 
```
Code Review - Error
realm does not allow editing name
```
- User can't manually add an email to their account since only auth is GH

**Comment by davido** [comment]
It should be possible to edit email. Exactly for this use case. There should be setting to allow this, that I forgot how t called exactly.

**Comment by bhcopeland** [comment]
@davido I have same problem. GitHub email is private, the user is populated with blank email but I get above error when setting email.

What is the setting to allow for this to be editable?

**Comment by davido** [comment]
@bhcopeland Yeah, exactly:

```
[oauth]
    allowRegisterNewEmail = true
```

thanks for providing the solution ;-)
